web:
  build: ./build/web/
  links:
    - db
  ports:
    - "8080:80"
  volumes:
    - "./html:/var/www/html"
    - "./log_web/:/var/log/apache2"
  expose:
    - 8080
db:
  build: ./build/db/
  ports:
    - "3306:3306"
  expose:
    - 3306
  volumes:
    - "./mysql_data:/var/lib/mysql"
    - "./log_db/:/var/log/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=sample
    - MYSQL_USER=sample
    - MYSQL_PASSWORD=sample
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
