web:
  build: .
  links:
    - db
  ports:
    - "80:80"
  volumes:
    - "./web:/var/www/html"
  expose:
    - "80"
db:
  image: "mysql:latest"
  ports:
    - "3306:3306"
  expose:
    - "3306"
  volumes:
    - "./web/mysql_data:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD="root"
